using System.Text.RegularExpressions;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterLiveSearch.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Tweets : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Views\Home\_Tweets.cshtml"

     new public dynamic Model { get; set; }
        #line default
        #line hidden

        public override void Execute()
        {


            
            #line 7 "..\..\Views\Home\_Tweets.cshtml"
 foreach(var tweet in Model.statuses)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"tweet\">       <img class=\"tweet_image\" src=\"");


            
            #line 10 "..\..\Views\Home\_Tweets.cshtml"
                                 Write(tweet.user.profile_image_url);

            
            #line default
            #line hidden
WriteLiteral("\" />        <span class=\"tweet_name\">");


            
            #line 11 "..\..\Views\Home\_Tweets.cshtml"
                            Write(tweet.user.name);

            
            #line default
            #line hidden
WriteLiteral("</span><span class=\"tweet_screen_name\">&#64;");


            
            #line 11 "..\..\Views\Home\_Tweets.cshtml"
                                                                                        Write(tweet.user.screen_name);

            
            #line default
            #line hidden
WriteLiteral("</span>       <br /><span class=\"tweet_text\">");


            
            #line 12 "..\..\Views\Home\_Tweets.cshtml"
                                  Write(tweet.text);

            
            #line default
            #line hidden
WriteLiteral("</span>       <br /><span class=\"tweet_date\">");


            
            #line 13 "..\..\Views\Home\_Tweets.cshtml"
                                  Write(tweet.created_at);

            
            #line default
            #line hidden
WriteLiteral("</span>    </div>");


            
            #line 15 "..\..\Views\Home\_Tweets.cshtml"
    
}
            
            #line default
            #line hidden

        }

    }
}


#pragma warning restore 1591
